version: '3.8'

services:

    jenkins:
        container_name: jenkins-66470
        hostname: jenkins
        build:
            context: .
            dockerfile: jenkins.Dockerfile
        image: jenkins:JENKINS-66470
        ports:
            - 8080:8080
        volumes:
            - jenkins-data:/var/jenkins_home

volumes:
    jenkins-data:
        